spring:
  application:
    name: student-service
server:
  port: 8001
logging:
  level:
    com.eurekaclient.example: DEBUG
eureka:
  client:
    service-url:
      defaultZone:  http://localhost:8761/eureka/
    healthcheck:
      enabled: true
  instance:
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 2
      
