spring:
  application:
    name: school-service
server:
  port: 8002
eureka:
  client:
    service-url:
      defaultZone:  http://localhost:8761/eureka/
    healthcheck:
      enabled: true
  instance:
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 2
logging:
  level:
    com.eureka.client.example: DEBUG
